### ISSUE TITLE
Deprecated inbuilt datasets for scRNAseq package used in Introduction to SCONE

### ISSUE THREAD

**Issue by biancamocanu** [YosefLab/scone#103]
Hello,

I'm opening this issue to let you know that when trying to import the fluidigm dataset used in the scone [example from the intro](https://bioconductor.org/packages/release/bioc/vignettes/scone/inst/doc/sconeTutorial.html), the scRNAseq package function ReprocessedFluidigmData() that retrieves the dataset is not defined in the latest version of scRNAseq anymore. Instead, it relies on retrieving datasets directly from ExperimentHub.

It's mentioned in the scRNAseq package update news [here](https://www.bioconductor.org/packages/release/data/experiment/news/scRNAseq/NEWS).

I didn't want to send an unsolicited pull request, so maybe you can update the source of that example dataset :)
Thank you for all your work!

**Comment by drisso** [comment]
Hi @biancamocanu 

I’m a bit confused. We updated the latest version of the vignette to use the new ReprocessedFluidigmData() function which relies on ExperimentHub. The deprecated way is to use data(fluidigm), which will stop running in the next release.

So, do you have issues compiling the vignette? If so, what version of Bioconductor are you using? The latest version (I believe 3.10) should work.

**Comment by biancamocanu** [comment]
Hello!

I had everything latest version, except Bioconductor, which was at 3.9. I tried this on my laptop, workstation and on a Mac, which is why I opened the issue in the first place...
I upgraded it now and the functions seems to work. 
Thank you for your help and swift reply!
