### ISSUE TITLE
ZINB FNR estimation does not always converge

### ISSUE THREAD

**Issue by drisso** [YosefLab/scone#33]

**Comment by mbcole** [comment]
Will be fixed upon switching zinb to pending zinb package
ZINB does not always converge as implemented and should be monitored closely if used

**Comment by drisso** [comment]
After discussing with @mbcole, we decided to remove zinb as an imputation method, because this implementation was inefficient and did not always converge.

We are developing a zinb package elsewhere and we will eventually depend on that for the zinb imputation.

This is done with commit 8cbe329824d83c3410aeea3befd8b1ca41384384 in develop.
