### ISSUE TITLE
Stabilize PAM param interface

### ISSUE THREAD

**Issue by mbcole** [YosefLab/scone#47]
The user currently selects a range of k for pam clustering (passed to `fpc::pamk`) but the resulting `PAM_SIL` score is based on complex considerations of that range. A few options:

- Have the user select one value of `eval_kclust`.
- (Optional) automatic `eval_kclust` selection.
- Permit a range of `eval_kclust`, but limit options and/or wrap `pamk` more effectively.

**Comment by drisso** [comment]
This was addressed a while ago.
