### ISSUE TITLE
R version documentation

### ISSUE THREAD

**Issue by TimothyTickle** [YosefLab/scone#52]
It seems that R >= 3.3 is required for the library. If this is true, it would be helpful to put that information at the install instructions.

Have a great day!

**Comment by drisso** [comment]
Thanks for the feedback!

Note that the DESCRIPTION file lists R >= 3.3 as a dependency, but I agree that this is not obvious / clear at a first glance. I will add a few lines to the README file.

**Comment by drisso** [comment]
Done!
