### ISSUE TITLE
S4 Interface for SCONE

### ISSUE THREAD

**Issue by mbcole** [YosefLab/scone#58]
Slots
- [x] Original Matrix
- [x] QC Matrix
- [x] Bio
- [x] Batch
- [x] Positive Controls
- [x] Negative Controls 1
- [x] Negative Controls 2
- [x] List of Normalized Matrices
- [x] File pointer to hdf5 (Alternative) 
- [x] List of Design Matrices (Depend on Bio and/or Batch)
- [x] List of List of Functions (Impute and Scale)
- [x] Additional Params or Flags  or Arguments (e.g. rezero? and Impute_Args)
- [x] Metrics
- [x] Scores
- [x] Params

Methods

- [x] `get_normalized()`: Returns expression matrix for normalized matrix requested (index of params)
- [x] `biplot_interactive()`: Interactive bi-plot returns smaller SCONE object based on user selection. Calls `selectMethods()`.
- [x] `[()`: Accessing subsets of cells or genes.
- [x] `select_methods()`: Accessing subsets of normalizations - look at summarized experiment.
- [x] `get_design()`: Returns design matrix.
- [x] `init_report()`: Initialize all information required for generating interactive report.
- [x] `report()`: View report.
- [x] `write_report()`: Produce static report.
- [x] `scone()`: Run all normalizations (store hdf5, in_memory, or not) and score.

**Comment by drisso** [comment]
Add a method for extracting and replacing `scone_params`: `get_params` and `set_params`

**Comment by drisso** [comment]
Remove scone_ from slot names

**Comment by drisso** [comment]
Add method for extracting metrics and scores

**Comment by drisso** [comment]
We should add `rezero` as a slot of the scone object and use it in get_normalized() to get consistent results when imputing.

**Comment by drisso** [comment]
Commits 4b6fc70aa095e31e5ae290ce53eaa0bfeb84646a..d7db5273802514f454a4abd88d55eb7c2e026614
