### ISSUE TITLE
allow non-default BPPARAM

### ISSUE THREAD

**Issue by allonw** [YosefLab/scone#62]
To allow a user to limit scone's core usage in multicore or to register a cluster

Add BPPARAM=my_BPPARAM to every use of bplapply etc. and add my_BPPARAM=bpparam() to the function definition as recommended in biocparallel

**Comment by drisso** [comment]
This is now implemented in develop (commit cdff261251d145c4dd2cae67660a20f5f320a65d).
By default, i.e., if no bpparam is specified, it uses the value of registered().
