### ISSUE TITLE
Add wrapper for scran

### ISSUE THREAD

**Issue by drisso** [YosefLab/scone#70]

**Comment by drisso** [comment]
Closed by 38c19dcd02e7307b6829d0dac165c4caaf022eba in develop

**Comment by mbcole** [comment]
Must re-introduce @ckmah 's wrapper with additional automation / modified argument interface

**Comment by ckmah** [comment]
There is a case where the internal clustering step `quickCluster` may break if there are too few cells (less than default minimum threshold of 200). Similarly `computeSumFactors` has a minimum threshold of some sort as well. @mbcole If this isn't too urgent I would be happy to investigate.

**Comment by mbcole** [comment]
I've added a non-clustering scran scaling function in 5c41e3d8fc1b95ad245ce75efb2cd47593b79844 but I think we will ultimately want to pass arguments to a wrapper similar to your original. I've added a new issue for this: #84
