### ISSUE TITLE
Scone not working on R 3.3.2 on MacOS

### ISSUE THREAD

**Issue by festeneam** [YosefLab/scone#77]
I like to do a lot of the plotting (and reshuffling and replotting) on my laptop, which works great for every program but Scone, which I cannot install on my "Sincere Pumpkin Patch R 3.3.2". 
Scone is very demanding: "ERROR: this R is version 3.3.2, package 'scone' requires R >= 3.4", while the README says R>=3.3. Bioconductor is adequately updated and there is no R 3.4 for MacOS. 
Is there a way to run Scone on a MacOS?

**Comment by mbcole** [comment]
Hi festeneam, 

Thanks for working with `scone`: we are currently in the process of submitting our package to Bioconductor, requiring R version 3.4 (currently in development) in the `master` branch. In the mean time, please consider checking out an earlier version of the master branch before the DESCRIPTION file was modified for the submission (c9cd07e15f9a508ee5b9b18e20a0d77737931c69).

Best,

Michael

**Comment by drisso** [comment]
There's no need to checkout an earlier version of the tree. You can simply download the [current release](https://github.com/YosefLab/scone/releases/tag/v0.99.0) which will work with R 3.3

**Comment by drisso** [comment]
I've updated the README with the new instructions

**Comment by festeneam** [comment]
This works, thank you very much! It does requires installing 'scran' first.

2016-11-28 13:46 GMT-05:00 Davide Risso <notifications@github.com>:
