### ISSUE TITLE
log = TRUE option for get_normalized returns the natural log?

### ISSUE THREAD

**Issue by cypranowska** [YosefLab/scone#95]
I usually log2 transform (with a pseudocount) my normalized expression data before doing further work, and was surprised to find that the log = TRUE option for get_normalized returns the log1p transformed matrix. 

Would it be possible to make a log2(x+1) option for get_normalized? Or explicitly mention that the natural log is returned in the documentation?

**Comment by mbcole** [comment]
Hi @cypranowska - thank you for your feedback! I think we can ultimately address this space with user-provided log-transformations and inverses. This would become an additional argument for modifying the adjustment step, stored internally for future use. In the meantime we can improve our documentation of the log-transformation / inverse (`log1p`,`exp1m`) being used in this package.

**Comment by cypranowska** [comment]
Thank you!
