### ISSUE TITLE
House keeping genes

### ISSUE THREAD

**Issue by emmanuelsapin** [YosefLab/scone#97]
Dear Yosef,
Thank you so much for this library.
However when I try to get the housekeeping genes and type:
print(data(housekeeping))
I get:
[1] "housekeeping"
Please could you tell me what did I do wrong?
Thank you in advance,
Cheers,
Emmanuel

**Comment by diyadas** [comment]
not a member of the lab, but

`?data` tells you that the value of a call to `data` is " A character vector of all data sets specified..."

`get(data(housekeeping))` will print the list of housekeeping genes, i.e. _get_ the contents of the list called `housekeeping` that is loaded into the workspace by `data(housekeeping)`
